### ISSUE TITLE
AttributeError: module 'jax.random' has no attribute 'PRNGKeyArray'

### ISSUE THREAD

**Issue by Aki1991** [google-research/scenic#1089]
Hi all, I am trying to fine tune our model using [owl_vit model](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit). 

But when I try to run it, I get this error, `AttributeError: module 'jax.random' has no attribute 'PRNGKeyArray'`. Jax version I am using is 0.4.30. If I use jax 0.4.23, it works but then it is not using GPU while training which slows down the training a lot. Is there a way I can use 0.4.30 version of jax and solve this error?

If I change the PRNGKeyArray with key, at later stage I get an error, `flops = analysis['flops']
TypeError: 'NoneType' object is not subscriptable`. 

Can anyone suggest what can I do here? Thank you.

**Comment by dr4thmos** [comment]
Same issue there.

**Comment by Aki1991** [comment]
`AttributeError: module 'jax.random' has no attribute 'PRNGKeyArray'` can be solved by changing `jax.random.PRNGKeyArray` with `jax.Array`. 

But it is not solving 
```
flops = analysis['flops']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by LihanWa** [comment]
This should be fixed in ott-jax==0.3.1

**Comment by Aki1991** [comment]
I am using same version of ott-jax==0.3.1, still same error.

**Comment by LihanWa** [comment]
sorry, it should be running "pip install ott-jax==0.4.5" firstly, if you have an error about "transport" then run "pip install ott-jax==0.3.1"

**Comment by Aki1991** [comment]
Yes I am getting the "transport" error, that's why I am using ott-jax==0.3.1. And that leads to same error again. 

```
flops = analysis['flops']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by thecho7** [comment]
pip install ott-jax==0.2.0 works

**Comment by TTy32** [comment]
None of the ott-jax versions work for me:

`pip install ott-jax==0.4.5`

```
    from ott.tools import transport
ImportError: cannot import name 'transport' from 'ott.tools' (/home/u/miniforge3/envs/scenic/lib/python3.10/site-packages/ott/tools/__init__.py)
```


`ott-jax==0.3.1`

```
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```


`pip install ott-jax==0.2.0`

```
  File "/home/u/scenic/scenic/common_lib/debug_utils.py", line 139, in compute_flops
    flops = analysis['flops']
TypeError: 'NoneType' object is not subscriptable
```

Any ideas? I have not idea how to continue

**Comment by TTy32** [comment]
Update: started with a clean `conda create -n myenv python=3.10`. After `pip install ott-jax==0.2.0` the error was gone.

* `CUDA 12.1`
* `Pytorch 2.5.1+cu121`
* Make sure to `LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64:$LD_LIBRARY_PATH`

**Comment by Zeying-Gong** [comment]
> sorry, it should be running "pip install ott-jax==0.4.5" firstly, if you have an error about "transport" then run "pip install ott-jax==0.3.1"

Thank you, that works for me!

**Comment by oksidgy** [comment]
python 3.10
Versions 0.4.5, 0.3.1, 0.2.0 don't work :(
